name: Planets Project CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        env:
            CI: true
            MONGO_URL: mongodb://localhost/planets
            GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
            GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}
            COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1 }}
            COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2 }}
        strategy:
            matrix:
                node-client-version: [ '14.3', '16' ]
                node-server-version: [ '20.12.2', '18' ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js for client version ${{ matrix.node-client-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-client-version }}
            -   name: MongoDB in GitHub Actions
                uses: supercharge/mongodb-github-action@1.11.0
                with:
                    mongodb-version: 7.0.9
            -   run: npm install --prefix ./client
            -   run: npm run build --prefix ./client
            -   run: npm run test --prefix ./client
            -   name: Use Node.js for server version ${{ matrix.node-server-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-server-version }}
            -   run: npm install --prefix ./server
            -   run: npm run test --prefix ./server

#    deploy:
#        needs: build
