name: Planets Project CI
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20.12.2'
            - run: npm install --prefix ./server
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.3'
            - run: npm install --prefix ./client
            - run: npm run build --prefix ./client
#    deploy:
#        needs: build
